### ISSUE TITLE
Development set retrieval results

### ISSUE THREAD

**Issue by GSidiropoulos** [henryzhao5852/BeamDR#1]
Dear authors,
Thank you very much for sharing your work. Could you please let me know why there are only 5904 questions, and not 7405, in sec_dev_retrieval.pkl?
Best regards,
Georgios

**Comment by henryzhao5852** [comment]
Hi, thanks for the interest and sorry for the late reply! In second_dev_retrieval.pkl only includes bridge questions, while on comparison questions we only single retrieval step.
